### PR TITLE
feat: 🎸implement basic user registration and login

### PR DESCRIPTION
**Pull request by fufuShih**
See #4

### CODE REVIEW

**Comment by fufuShih** [comment]
不確定為何要使用MongoClient，而不是使用mongoose去連接db，不是使用mongoose操作資料庫嗎?
https://github.com/ChillKa/chillka-backend/blob/2024d0515919acb12a2113bca9b5645da7317b5a/src/app.ts#L12-L22

**Comment by miamai** [comment]
> 不確定為何要使用MongoClient，而不是使用mongoose去連接db，不是使用mongoose操作資料庫嗎?
> 
> https://github.com/ChillKa/chillka-backend/blob/2024d0515919acb12a2113bca9b5645da7317b5a/src/app.ts#L12-L22

用mongoose就可以了，之前沒連上所以我用client試。已刪除在`fix: remove redundant mongodb client`

**Comment by miamai** [comment]
Update new commit of [feat: update erorr constructor, simple validation regex](https://github.com/ChillKa/chillka-backend/pull/5/commits/5e1ddb36332a449ca1807b2229a11c859d315948):
- catch error message
  - construct a new `CoreError` for backend self-defined error message
  - construct `throwAPIError` for throwing out 500 server error if not using CoreError ( since you have defined the MVC, it's currently what I came out with to align the structure and catch the server error🙇‍♀️
- update simple email and phone validation regex
- update login error status code to 400
  - 401 more like didn't have auth token append in header when call a api?

@fufuShih please review, thanks🙌

*Your APIs work good btw

**Comment by miamai** [comment]
LGTM

**Review by miamai — APPROVED** [review]

**Pull request merged**
